
snd-soc-canaan-audio-objs := canaan_audio.o

obj-$(CONFIG_SND_SOC_CANAAN_AUDIO) += snd-soc-canaan-audio.o

snd-soc-canaan-max98090-objs := canaan_max98090.o 

obj-$(CONFIG_SND_SOC_CANAAN_MAX98090) += snd-soc-canaan-max98090.o

snd-soc-canaan-nau8822-objs := canaan_nau8822.o 

obj-$(CONFIG_SND_SOC_CANAAN_NAU8822) += snd-soc-canaan-nau8822.o
