# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_PLAT_AE350) += ae350_ax45mp.dtb \
                            ae350_a45mp.dtb \
                            ae350_ax45mp_octa_sf.dtb
obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
