k510-isp-objs += isp_mipi/csi2/mipi_csi2.o isp_mipi/dphy/mipi_dphy.o
k510-isp-objs += vi/vi.o vi/wrap/vi_wrap_drv.o vi/pipe/vi_pipe_drv.o
k510-isp-objs += isp_2k/table/isp_gamma_table.o  isp_2k/table/isp_wdr_table.o \
				 isp_2k/ds/isp_ds_coeff.o
k510-isp-objs += isp_2k/core/isp_f2k_core_drv.o isp_2k/ds/isp_f2k_ds_drv.o \
				 isp_2k/wrap/isp_f2k_wrap_drv.o isp_2k/fbc/isp_3dnr_fbc_drv.o\
				 isp_2k/fbd/isp_3dnr_fbd_drv.o isp_2k/remap/isp_f2k_remap_drv.o \
				 isp_2k/table/isp_f2k_table_drv.o isp_2k/isp_f2k.o
k510-isp-objs += isp_2k/core/isp_r2k_core_drv.o isp_2k/ds/isp_r2k_ds_drv.o \
				 isp_2k/wrap/isp_r2k_wrap_drv.o isp_2k/remap/isp_r2k_remap_drv.o\
				 isp_2k/table/isp_r2k_table_drv.o isp_2k/isp_r2k.o
k510-isp-objs += isp_2k/isp_3a/isp_f2k_ae.o isp_2k/isp_3a/isp_f2k_af.o isp_2k/isp_3a/isp_f2k_awb.o\
				 isp_2k/isp_3a/isp_r2k_ae.o isp_2k/isp_3a/isp_r2k_af.o isp_2k/isp_3a/isp_r2k_awb.o
k510-isp-objs += k510isp_video.o k510_isp.o k510isp_stat.o 
obj-$(CONFIG_VIDEO_CANAAN_K510) += k510-isp.o 
