obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_CRYP) += kendryte_crypto.o
kendryte_crypto-objs := kendryte-aes.o 
obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_HASH) += kendryte_hash.o
kendryte_hash-objs := kendryte-hash.o
obj-$(CONFIG_CRYPTO_DEV_KENDRYTE_TRNG) += kendryte_trng.o
kendryte_trng-objs := kendryte-trng.o

